context:
  version: "0.27.6"

package:
  name: typedoc
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typedoc/-/typedoc-${{ version }}.tgz
  sha256: ae55e53af2dadbcea90a0c10615fcf3e5a706c509cc4be90c3f00de60333ac98

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - typedoc --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Documentation generator for TypeScript projects.
  homepage: https://github.com/TypeStrong/typedoc
  repository: https://github.com/TypeStrong/typedoc

extra:
  recipe-maintainers:
    - danielnachun
