context:
  version: "0.28.1"

package:
  name: typedoc
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typedoc/-/typedoc-${{ version }}.tgz
  sha256: ad8b6801994efc4dcab0eea1f923117f44b68d0635e3b0f76039de44dfffe1e6

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - typedoc --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Documentation generator for TypeScript projects.
  homepage: https://github.com/TypeStrong/typedoc
  repository: https://github.com/TypeStrong/typedoc

extra:
  recipe-maintainers:
    - danielnachun
