context:
  version: "0.28.11"

package:
  name: typedoc
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/typedoc/-/typedoc-${{ version }}.tgz
  sha256: 443d03436a47c3538e59eef951e4d0c19a79138f2e9f886b267279ae15e77954

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - typedoc --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Documentation generator for TypeScript projects.
  homepage: https://github.com/TypeStrong/typedoc
  repository: https://github.com/TypeStrong/typedoc

extra:
  recipe-maintainers:
    - danielnachun
